Repository red-ant/redant-home, pull requests merged in 2023-02, with the labels that each got.

#308 Remove GA id [RAM-253]
  _config.yml
Labels: Merge

#309 Space out buttons on mobile
  _includes/blog-nav.html
Labels: Merge

#310 Updated action to latest jekyll with deploy action
  .github/workflows/build-and-deploy.yml
Labels: Dev Release

#302 Stripe assessment tool [RAM-247]
  .forestry/front_matter/templates/posts.yml
  _data/assessment.json
  _data/results.json
  _emails/assessment-email.html
  _includes/assessment/answers.html
  _includes/assessment/header.html
  _includes/assessment/questions.html
  _includes/assessment/sections.html
  _includes/blog-nav.html
  _includes/posts-by-category-online-payments.html
  _layouts/assessment.html
  _pages/assessment.html
  _pages/assessment/current.html
  _pages/assessment/owner.html
  _pages/assessment/results.html
  _pages/assessment/submit.html
  _pages/assessment/technology.html
  _pages/assessment/your-team.html
  _pages/ideas.html
  _pages/news.html
  _pages/online-payments.html
  _posts/2023-02-08-different-levels-of-payment-maturity.md
  _posts/2023-02-08-how-well-does-your-business-do-online-payments.md
  _posts/2023-02-08-payments-case-study.md
  _posts/2023-02-08-payments-implementation-scale.md
  _posts/2023-02-08-road-to-digital-payments-success.md
  _src/application.js
  _src/controllers/assessment-controller.js
  _src/controllers/index.js
  _src/stylesheets/_assessment.scss
  _src/stylesheets/_borders.scss
  _src/stylesheets/_buttons.scss
  _src/stylesheets/_layout.scss
  _src/stylesheets/_nav.scss
  _src/stylesheets/_sections.scss
  _src/stylesheets/_text.scss
  _src/stylesheets/_tiles.scss
  _src/stylesheets/_variables.scss
  _src/stylesheets/application.scss
  assets/images/stripe/bg.png
  assets/images/stripe/device.png
  assets/uploads/2023/how-well-does-your-business-do-online-payments-min.png
  assets/uploads/2023/payments-case-study-min.png
  assets/uploads/2023/payments-implementation-scale-min.png
  assets/uploads/2023/tool-min.png
  assets/uploads/2023/what-are-the-different-levels-of-payment-maturity-min.png
  assets/uploads/2023/where-to-start-on-the-road-to-digital-payments-success-min.png
Labels: Merge, Dev Release

#312 Fix mail validation
  _src/controllers/assessment-controller.js
Labels: Merge, Hotfix

#313 Add tracking & fix email image [RAM-247]
  _emails/assessment-email.html
  _pages/assessment.html
  _pages/assessment/results.html
  _pages/assessment/submit.html
Labels: Merge

#314 Remove unused dependency
  README.md
  package.json
  yarn.lock
Labels: Merge
