Repository red-ant/redant-home, pull requests merged in 2023-05, with the labels that each got.

#322 Add MS clarity tracking code [RAM-270]
  _config.yml
  _includes/head.html
  _includes/tracking.html
Labels: Merge, Dev Release

#325 Update tinaCMS version [RAM-271]
  .tina/__generated__/_graphql.json
  .tina/__generated__/_schema.json
  package.json
  yarn.lock
Labels: Merge, Dev Release

#329 Fix description copy
  _pages/portfolio.html
Labels: Merge, Hotfix

#331 Update portfolio.html
  _pages/portfolio.html
Labels: Merge

#316 Add new assessment pages [RAM-258, RAM-260]
  .tina/__generated__/_schema.json
  _book_call/cybersecurity.md
  _book_call/payment.md
  _book_call/privacy.md
  _config.yml
  _data/assessment.json
  _data/results.json
  _email_layouts/cybersecurity-email.html
  _email_layouts/payment-email.html
  _email_layouts/privacy-email.html
  _includes/assessment/header.html
  _includes/assessment/questions.html
  _includes/assessment/sections.html
  _includes/blog-nav.html
  _includes/posts-by-category-online-payments.html
  _includes/posts-by-category.html
  _layouts/book-call.html
  _layouts/results.html
  _layouts/section.html
  _layouts/submit.html
  _pages/assessment/current.html
  _pages/assessment/owner.html
  _pages/assessment/technology.html
  _pages/assessment/your-team.html
  _pages/online-payments.html
  _pages/payment-maturity-assessment.html
  _pages/privacy-maturity-assessment.html
  _pages/privacy.html
  _pages/security-maturity-assessment.html
  _results/cybersecurity.md
  _results/payment.md
  _results/privacy.md
  _sections/access-and-correction.md
  _sections/collection-and-use.md
  _sections/current.md
  _sections/detect.md
  _sections/disclosure.md
  _sections/govern.md
  _sections/owner.md
  _sections/protect.md
  _sections/protection.md
  _sections/respond.md
  _sections/technology.md
  _sections/your-team.md
  _src/controllers/assessment-controller.js
  _src/stylesheets/_assessment.scss
  _src/stylesheets/_nav.scss
  _src/stylesheets/_variables.scss
  _submissions/cybersecurity.md
  _submissions/payment.md
  _submissions/privacy.md
  assets/images/assessment/bg.png
  assets/images/assessment/device.png
  package.json
  yarn.lock
Labels: Merge, Dev Release

#332 Update cyber-security.html
  _pages/cyber-security.html
Labels: Merge

#333 Update jobs.html
  _pages/jobs.html
Labels: Merge

#335 Hide privacy page & cyber security assessment
  _includes/blog-nav.html
  _includes/posts-by-category.html
  _pages/privacy.html
Labels: Merge, Dev Release

#334 Update sitemap pages [RAM-274]
  _pages/on-demand/backend-ruby-on-rails.html
  _pages/on-demand/design-ux.html
  _pages/on-demand/frontend-javascript.html
  _pages/on-demand/index.html
  _pages/on-demand/ios-native-swift.html
  _pages/on-demand/terms-of-service.html
  _pages/on-demand/thank-you/backend.html
  _pages/on-demand/thank-you/frontend.html
  _pages/on-demand/thank-you/ios.html
  _pages/on-demand/thank-you/ux-backend.html
  _pages/on-demand/thank-you/ux-frontend.html
  _pages/on-demand/thank-you/ux-ios.html
  _pages/on-demand/thank-you/ux.html
Labels: Merge, Dev Release

#339 Add new frontmatter fields to projects
  .tina/__generated__/_graphql.json
  .tina/__generated__/_schema.json
  .tina/config.js
  _layouts/project.html
  portfolio/12wbt-daily-app.md
  portfolio/12wbt-dynamic-video.md
  portfolio/12wbt-recipes.md
  portfolio/12wbt.md
  portfolio/accr.md
  portfolio/bank-of-queensland.md
  portfolio/beautyheaven-beautorium.md
  portfolio/beautyheaven.md
  portfolio/bondi-vet.md
  portfolio/campaign-xpress.md
  portfolio/gigcar.md
  portfolio/huggies.md
  portfolio/know-anyone.md
  portfolio/managed.md
  portfolio/matrix-education.md
  portfolio/mentored.md
  portfolio/move.md
  portfolio/mup.md
  portfolio/nps-medicinewise.md
  portfolio/outdoor-automated-proposal-platform.md
  portfolio/pearsons-florist.md
  portfolio/pearsons-nav-admin.md
  portfolio/pearsons-school-of-floristry.md
  portfolio/placeos.md
  portfolio/project-summary-tool.md
  portfolio/selleys-diy.md
  portfolio/smata.md
  portfolio/sydney-trains.md
  portfolio/the-grants-hub.md
  portfolio/tribe-influencer-marketplace.md
  portfolio/whats-on.md
  portfolio/yates.md
Labels: Dev Release
